services:
  - type: web
    name: tweeter-clone
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: APP_KEY
        generateValue: true
      - key: DRIVE_DISK
        value: local
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_VIEWS
        value: true
      - key: DB_CONNECTION
        value: pg
      - key: NODE_VERSION
        value: 18.x
